Modify nameservers and search domains in place
os-net-config/os-net-config pull request #105
Opened 2024-10-07 00:09 UTC by karthiksundaravel

Added the ability to modify DNS servers as well as DNS search domains on the fly. Also cleaned up code and updated much of the string handling for Python3.

2024-10-07 05:00 UTC, vcandapp requested changes

2024-10-07 06:07 UTC, dsneddon approved these changes

2024-10-07 06:12 UTC, dsneddon commented on os_net_config/impl_ifcfg.py
> +        if 'DOMAIN' in changes:
Viji,

This file is going to be overwritten every time the interface is brought up. When the user reboots this file will be overwritten, so there is no reason to add the comment that you requested.

2024-10-07 06:14 UTC, vcandapp approved these changes
lgtm

2024-10-07 08:28 UTC, vcandapp commented on os_net_config/impl_ifcfg.py
> +            new = data_values['DOMAIN']
Domain should be like https://github.com/os-net-config/os-net-config/blob/master/os_net_config/impl_ifcfg.py#L759

2024-10-09 13:35 UTC, karthiksundaravel commented
Abandonned

2024-10-09 13:35 UTC, closed without merging