ignore VFs defined
os-net-config/os-net-config pull request #131
Opened 2024-11-20 14:29 UTC by SharonBX

currently os-net-config fail to rerun in case config.json not includes sriov VF definitions (or sriov been defined on the host without nmstate ) the fail reason is the desire VFs hard coded to zero is not as current.
this pr will replace the zero with current defined VFs to avoid the fail verification.

2024-11-25 10:36 UTC, karthiksundaravel requested changes
Its tricky one and I'll have to check how this patch fits the other Openstack use cases.

2024-11-25 10:36 UTC, karthiksundaravel commented on os_net_config/impl_nmstate.py
> +from os_net_config import sriov_config
Don't import sriov_config here. The numvfs could be obtained from the iface_state() itself.

2024-12-05 23:26 UTC, dsneddon approved these changes

2024-12-05 23:26 UTC, dsneddon approved these changes

2024-12-10 05:07 UTC, dsneddon approved these changes
This looks good to me, but I will wait for a review from Karthik before merging. Thanks!

2024-12-10 11:05 UTC, karthiksundaravel approved these changes

2024-12-10 11:34 UTC, merged