update README and doc content
os-net-config/os-net-config pull request #138
Opened 2024-12-20 11:17 UTC by vcandapp

This commit is to update all README and doc content related to os-net-config repo

2024-12-20 12:01 UTC, karthiksundaravel commented
Please address the check commit issues.
Run ./check-commits "47a3903fbb0740b09fe8fc6ab898c45aeff9c7d0..a25309e26be619598eb6d49d42485c06824cd58b"
error [1/1] 'update README and doc content' title lacks a lowercase topic prefix (e.g. 'ipv6:')
error [1/1] 'update README and doc content' 'Signed-off-by: vcandapp <vcandapp@redhat.com>' trailer is missing
error [1/1] 'update README and doc content' body has less than three words, please describe your changes

2024-12-20 15:40 UTC, vcandapp commented
recheck

2024-12-23 05:47 UTC, vcandapp commented
recheck

2024-12-23 10:44 UTC, vcandapp commented
recheck

2025-01-06 03:56 UTC, karthiksundaravel requested changes
Typo in commit message "doc: update readma description"

2025-01-06 04:13 UTC, vcandapp commented
> Typo in commit message "doc: update readma description"

Fixed

2025-01-06 04:18 UTC, karthiksundaravel submitted a review, later dismissed
Thanks. LGTM!

2025-01-20 15:40 UTC, dsneddon requested changes
Thanks for this, but can you make a couple of minor changes (see comments)

2025-01-20 15:40 UTC, dsneddon commented on README.rst
> +    :target: https://governance.openstack.org/tc/reference/projects/
Unfortunately os-net-config isn't listed as a project team at that URL, and neither is TripleO anymore.

2025-01-20 15:40 UTC, dsneddon commented on README.rst
> +backend configuration providers (One of: ifcfg, eni, nmstate, iproute).
This should probably read:

backend configuration providers, one of: ifcfg (network-init-scripts), nmstate (NetworkManager), or eni (basic support for /etc/network/interfaces)

We never implemented iproute.

2025-01-20 15:40 UTC, dsneddon commented on README.rst
>  * Documentation: https://docs.openstack.org/os-net-config/latest
It's not important for this PR, but we should probably move the latest docs to GitHub and point there in a follow-up

2025-01-21 15:22 UTC, vcandapp commented on README.rst
> +    :target: https://governance.openstack.org/tc/reference/projects/
Should we add os-net to the projects ? But will remove this section as of now

2025-01-22 07:43 UTC, dsneddon approved these changes
Thanks!

2025-01-22 07:49 UTC, karthiksundaravel approved these changes

2025-01-22 07:49 UTC, merged