Sriov pci address
os-net-config/os-net-config pull request #142
Opened 2024-12-26 14:04 UTC by karthiksundaravel

sriov: add pci address and mac address in sriov map
SR-IOV PF's pci address and mac address shall be stored
in the map, so that when the PF is attached to the guest, the
PF's details coud be read.

Signed-off-by: Karthik Sundaravel <ksundara@redhat.com>

2025-01-14 15:20 UTC, rjarry requested changes
one mistakenly committed patchfile and also you need to rebase on top of #139 ?

2025-01-14 15:20 UTC, rjarry commented on 0001-sriov-add-pci-address-and-mac-address-in-sriov-map.patch
> +From 3a6fc3285e676b61c1bbdcaf976b332fdbee665f Mon Sep 17 00:00:00 2001
this file was probably committed by mistake :)

2025-01-14 15:45 UTC, rjarry approved these changes

2025-01-17 08:12 UTC, vcandapp commented
> sriov: add pci address and mac address in sriov map SR-IOV PF's pci address and mac address shall be stored in the map, so that when the PF is attached to the guest, the PF's details coud be read.
> 
> Signed-off-by: Karthik Sundaravel [ksundara@redhat.com](mailto:ksundara@redhat.com)

@karthiksundaravel , can you please link the Jira here

2025-01-17 09:31 UTC, karthiksundaravel commented
Viji,
FFU and minor updates could be covered when we get baremetal testing in place.
Jira: https://issues.redhat.com/browse/OSPRH-12024

2025-01-20 09:47 UTC, vcandapp approved these changes
LGTM

2025-01-20 09:48 UTC, merged