Nic part driver autoprobe
os-net-config/os-net-config pull request #145
Opened 2024-12-30 10:19 UTC by karthiksundaravel

sriov: Handle NIC partitioning while autoprobe is disabled
    
When drivers_autoprobe is disabled for sriov_pf, the VFs created
will not be bound with the required net drivers and hence those
VFs would not be listed in the /sys/class/net/<vf name>.
In order to make the NIC partitioning functional the required drivers
needs to be bounded with the VF.

2025-01-14 15:48 UTC, rjarry approved these changes
rebase on top of #142 and #144 and LGTM :)

2025-01-14 15:51 UTC, rjarry requested changes

2025-01-22 18:54 UTC, dsneddon commented on os_net_config/objects.py
> +        common.set_driverctl_override(pci_address, driver)
That's a good idea

2025-03-26 05:51 UTC, rjarry requested changes

2025-03-26 05:51 UTC, rjarry commented on os_net_config/utils.py
> +def get_vf_devname(pf_name, vfid):
remove trailing whitespace

2025-04-07 11:42 UTC, vcandapp commented on os_net_config/common.py
> +    modalias_path = get_dev_path(pf_name, f"virtfn{vfid}/modalias")
Will noop() handling be needed here ?

2025-04-07 11:42 UTC, vcandapp commented on os_net_config/objects.py
> +            common.set_driverctl_override(pci_address, def_driver)
There is double call made to "get_pci_device_driver()" - one in L1610 and another inside set_driverctl_override(). Is there scope to optimize ?

2025-04-07 13:37 UTC, vcandapp commented
@karthiksundaravel , the Jira link to PR is missing

2025-04-07 16:15 UTC, karthiksundaravel commented on os_net_config/common.py
> +    modalias_path = get_dev_path(pf_name, f"virtfn{vfid}/modalias")
Its not needed. Its read only function and the unit tests shall stub this when required.

2025-04-08 06:42 UTC, vcandapp commented on os_net_config/common.py
> +    modalias_path = get_dev_path(pf_name, f"virtfn{vfid}/modalias")
Will this path exist for noop case ? Like  get_pci_device_driver() https://github.com/os-net-config/os-net-config/blob/master/os_net_config/common.py#L313 uses noop check - as the pci/sysfs will not exist right ?

2025-04-08 12:41 UTC, karthiksundaravel commented on os_net_config/common.py
> +    modalias_path = get_dev_path(pf_name, f"virtfn{vfid}/modalias")
noop is actually meant for dry run on the real hardware, so all the read actions should be acceptable. however the set_driverctl_override() will break the noop functionality. Lets handle this in a follow up PR as its unrelated to this.

2025-04-09 07:50 UTC, vcandapp approved these changes
LGTM

2025-04-15 08:44 UTC, rjarry approved these changes

2025-04-15 10:50 UTC, merged