sriov: force sriov_drivers_autoprobe=0
os-net-config/os-net-config pull request #18
Opened 2024-04-04 18:43 UTC by rjarry

By default, VFs are automatically bound to their default kernel driver after being created.  This leads to creating a new network interface (linux netdev) for every VF.  Every netdev consumes IRQs (for RX/TX queues and other operations).  This can cause a very large number of IRQ to be created alongside which all need to be handled by a host CPU. A single VF may consume more than 10 IRQs, depending on the driver.

Intel CPU APICs can only handle a limited amount of IRQ.  Basically, there are 256 interrupt vectors in the APIC.  55 of them are reserved for general purpose interrupts (exceptions, division by zero, etc.) That leaves 201 of them for hardware/device related MSI.

Using cpu_affinity, it is possible to control which IRQs are handled by which CPUs, up to this 201 limit.  Past that limit, the kernel will fail to map the IRQ to a CPU if its APIC is already full.  This will cause the IRQs to be bound to the next available CPU.

In OpenStack NFV deployments, it is frequent to use CPU isolation to ensure that no IRQ nor CPU steal can happen on cores that are dedicated for virtual machines.  If there are too many IRQs to pack in housekeeping cores, there will be overspilling in CPUs that are expected to be isolated.  This can lead to workload interruptions and in the end cause latency and performance issues.

In most cases, the VFs created by os-net-config are only meant for virtual machines and are no use to the host.  When the VF devices are assigned to a guest, they need to be bound to the vfio-pci driver anyway, effectively unbinding them from their default kernel driver. This in turn removes their associated linux netdev (and their related IRQs).  However, until they are bound to a guest, the unused VFs consume IRQs and can cause issues as described above.

Force sriov_drivers_autoprobe to 0 (the default value is 1) before setting sriov_numvfs.  This causes VF PCI devices to be created but prevents the kernel from binding them to their respective default driver, thus preventing the creation of netdevs and avoiding the need for CPUs to handle extraneous IRQs.

Link: https://bugzilla.redhat.com/2184735
Link: https://docs.kernel.org/PCI/pci-iov-howto.html#sr-iov-api

NB: I am pretty certain that this breaks some use cases but I have submitted this anyway to have a starting point for discussion.

2024-04-04 22:58 UTC, nhicher commented
Hello @rjarry,

Can you remove the depends-on for it break zuul on review.rdo. We hit github rate-limit for our github application is not present on nmstate repo.

Thanks

2024-04-05 06:55 UTC, rjarry commented
Hi @nhicher, I have changed it to `Link:` but the code actually depends on https://github.com/nmstate/nmstate/pull/2643. Without it, some checks will fail.

2024-06-24 12:56 UTC, rjarry commented
@karthiksundaravel could you have another look?

Thanks!

2024-06-26 04:27 UTC, karthiksundaravel approved these changes
Thanks

2024-07-10 15:41 UTC, karthiksundaravel commented on os_net_config/sriov_config.py
> +                autoprobe = pfs[0]['drivers_autoprobe']
please add a check if the dict has 'drivers_autoprobe' key

2024-08-09 14:59 UTC, vcandapp requested changes

2024-08-28 10:24 UTC, rjarry commented on os_net_config/sriov_config.py
> +def get_drivers_autoprobe(ifname):
I don't know about switchdev. It probably requires the VF to be probed but I could be wrong. I have not tested it.

2024-09-05 15:25 UTC, vcandapp approved these changes
lgtm

2024-09-05 15:34 UTC, vcandapp commented on os_net_config/sriov_config.py
> +def get_drivers_autoprobe(ifname):
As discussed, we will add some release notes like: "This flag should not be set for switchdev / vdpa / nicpartionined" devices"...

2024-09-05 16:19 UTC, karthiksundaravel approved these changes
lgtme. Thanks

2024-09-05 16:34 UTC, merged