Adding support for DSCP configuration
os-net-config/os-net-config pull request #23
Opened 2024-06-11 10:38 UTC by karthiksundaravel

Allow the user to do DSCP mapping for network objects Interface and SriovPF. The feature needs the handling of netlink messages. The pyroute2 module is used in the encode/decode of the netlink messages.
The persistence of the DSCP configurations are taken care by the os-net-config-dcb-config service. The user configurations are preserved in /var/lib/os-net-config/dcb_config.yaml

The details of the DSCP configurations could be read anytime with the cli.
``os-net-config-dcb --show``

The new DSCP configurations can be applied with cli using ``os-net-config-dcb --config <config.yaml>``

The sample config.yaml for updating DCB only is available at etc/os-net-config/samples/dcb_config_sample.yaml

(cherry picked from commit 3c11aef6d3dde83217a47b8a6d0e5f7f8018b2b2)

2024-08-09 15:02 UTC, vcandapp commented
recheck

2024-08-14 04:54 UTC, vcandapp requested changes

2024-08-14 06:50 UTC, karthiksundaravel commented on etc/os-net-config/samples/dcb_config_sample.yaml
> +# For reconfiguring the DCB, the below template could be used.
I'll raise another PR on master

2024-08-20 12:41 UTC, karthiksundaravel commented on etc/os-net-config/samples/dcb_config_sample.yaml
> +# For reconfiguring the DCB, the below template could be used.
Its handled by https://github.com/os-net-config/os-net-config/pull/46. And when its merged, I'll raise another PR for backport to stable/wallaby

2024-08-27 10:09 UTC, vcandapp approved these changes
lgtm

2024-08-27 10:10 UTC, merged