Handle nic mapping for DCB configs
os-net-config/os-net-config pull request #31
Opened 2024-07-17 13:37 UTC by abhiramnarayana

As part of deployment templates the nic numbering
is being used and for DCB configs it is not supported and expecting physical interface naming. Hence adding changes to use the mapping of the nics to appropriate interfaces for DCB configs, so that it can support with nic numbering.

Changes are done and tested as below. Logs shared for reference.
[cloud-admin@rhos-nfv-10 ~]$ sudo os-net-config -d 
2024-07-17 10:32:13.094 INFO os_net_config.main Using config file at: /etc/os-net-config/config.yaml
2024-07-17 10:32:13.095 INFO os_net_config.impl_ifcfg.__init__ Ifcfg net config provider created.
2024-07-17 10:32:13.095 INFO os_net_config.main Using mapping file at: /etc/os-net-config/mapping.yaml
2024-07-17 10:32:13.096 DEBUG os_net_config.main interface_mapping: {'nic1': 'e4:43:4b:4d:ec:64', 'nic2': 'e4:43:4b:4d:ec:46', 'nic3': '04:3f:72:d9:c0:44', 'nic4': '04:3f:72:d9:c0:45', 'nic5': 'e4:43:4b:4d:ec:44', 'nic6': 'e4:43:4b:4d:ec:65'}
2024-07-17 10:32:13.096 DEBUG os_net_config.main persist_mapping: False
2024-07-17 10:32:13.108 DEBUG os_net_config.main network_config: [{'type': 'linux_bond', 'name': 'bond_api', 'use_dhcp': False, 'bonding_options': 'mode=active-backup', 'dns_servers': ['192.168.122.80'], 'addresses': [{'ip_netmask': '192.168.122.101/24'}], 'routes': [{'default': True, 'next_hop': '192.168.122.1'}], 'members': [{'type': 'interface', 'name': 'nic2', 'primary': True}]}, {'type': 'vlan', 'vlan_id': 202, 'device': 'bond_api', 'addresses': [{'ip_netmask': '172.17.0.100/24'}], 'routes': []}, {'type': 'vlan', 'vlan_id': 203, 'device': 'bond_api', 'addresses': [{'ip_netmask': '172.18.0.100/24'}], 'routes': []}, {'type': 'ovs_user_bridge', 'name': 'br-link1', 'use_dhcp': False, 'mtu': 9000, 'members': [{'type': 'ovs_dpdk_port', 'name': 'dpdk1', 'driver': 'mlx5_core', 'mtu': 9000, 'members': [{'type': 'interface', 'name': 'nic3', 'dcb': {'dscp2prio': [{'priority': 2, 'protocol': 24}, {'priority': 3, 'protocol': 8}, {'priority': 4, 'protocol': 12}]}}]}]}, {'type': 'ovs_user_bridge', 'name': 'br-link2', 'use_dhcp': False, 'mtu': 9000, 'members': [{'type': 'ovs_dpdk_port', 'name': 'dpdk2', 'driver': 'mlx5_core', 'members': [{'type': 'interface', 'name': 'nic4', 'dcb': {'dscp2prio': [{'priority': 2, 'protocol': 24}, {'priority': 3, 'protocol': 8}, {'priority': 4, 'protocol': 12}]}}]}]}, {'type': 'interface', 'name': 'nic5', 'use_dhcp': False, 'use_dhcpv6': False}, {'type': 'interface', 'name': 'nic6', 'use_dhcp': False, 'use_dhcpv6': False}, {'type': 'interface', 'name': 'nic1', 'use_dhcp': True, 'use_dhcpv6': False}]
2024-07-17 10:32:13.386 INFO os_net_config.utils._ordered_nics Finding active nics
2024-07-17 10:32:13.387 INFO os_net_config.utils._ordered_nics enp4s0f1np1 is an active nic
2024-07-17 10:32:13.387 INFO os_net_config.utils._ordered_nics bonding_masters is not an active nic
2024-07-17 10:32:13.387 INFO os_net_config.utils._ordered_nics eno4 is an embedded active nic
2024-07-17 10:32:13.387 INFO os_net_config.utils._ordered_nics br-link2 is not an active nic
2024-07-17 10:32:13.388 INFO os_net_config.utils._ordered_nics lo is not an active nic
2024-07-17 10:32:13.388 INFO os_net_config.utils._ordered_nics eno2 is an embedded active nic
2024-07-17 10:32:13.388 INFO os_net_config.utils._ordered_nics tap27ad006e-80 is not an active nic
2024-07-17 10:32:13.388 INFO os_net_config.utils._ordered_nics vlan202 is not an active nic
2024-07-17 10:32:13.388 INFO os_net_config.utils._ordered_nics br-int is not an active nic
2024-07-17 10:32:13.388 INFO os_net_config.utils._ordered_nics ovs-netdev is not an active nic
2024-07-17 10:32:13.389 INFO os_net_config.utils._ordered_nics eno3 is an embedded active nic
2024-07-17 10:32:13.389 INFO os_net_config.utils._ordered_nics br-link1 is not an active nic
2024-07-17 10:32:13.389 INFO os_net_config.utils._ordered_nics eno1 is an embedded active nic
2024-07-17 10:32:13.389 INFO os_net_config.utils._ordered_nics bond_api is not an active nic
2024-07-17 10:32:13.390 INFO os_net_config.utils._ordered_nics enp4s0f0np0 is an active nic
2024-07-17 10:32:13.390 INFO os_net_config.utils._ordered_nics vlan203 is not an active nic
2024-07-17 10:32:13.391 INFO os_net_config.utils._ordered_nics enp4s0f0np0 is an DPDK bound nic
2024-07-17 10:32:13.391 INFO os_net_config.utils._ordered_nics enp4s0f1np1 is an DPDK bound nic
2024-07-17 10:32:13.391 INFO os_net_config.utils._ordered_nics Active nics are ['eno1', 'eno2', 'eno3', 'eno4', 'enp4s0f0np0', 'enp4s0f1np1']
2024-07-17 10:32:13.392 DEBUG os_net_config.objects.mapped_nics e4:43:4b:4d:ec:64 matches device eno3
2024-07-17 10:32:13.392 INFO os_net_config.objects.mapped_nics nic1 in mapping file mapped to: eno3
2024-07-17 10:32:13.392 DEBUG os_net_config.objects.mapped_nics e4:43:4b:4d:ec:46 matches device eno2
2024-07-17 10:32:13.392 INFO os_net_config.objects.mapped_nics nic2 in mapping file mapped to: eno2
2024-07-17 10:32:13.393 DEBUG os_net_config.objects.mapped_nics 04:3f:72:d9:c0:44 matches device enp4s0f0np0
2024-07-17 10:32:13.393 INFO os_net_config.objects.mapped_nics nic3 in mapping file mapped to: enp4s0f0np0
2024-07-17 10:32:13.393 DEBUG os_net_config.objects.mapped_nics 04:3f:72:d9:c0:45 matches device enp4s0f1np1
2024-07-17 10:32:13.393 INFO os_net_config.objects.mapped_nics nic4 in mapping file mapped to: enp4s0f1np1
2024-07-17 10:32:13.393 DEBUG os_net_config.objects.mapped_nics e4:43:4b:4d:ec:44 matches device eno1
2024-07-17 10:32:13.394 INFO os_net_config.objects.mapped_nics nic5 in mapping file mapped to: eno1
2024-07-17 10:32:13.394 DEBUG os_net_config.objects.mapped_nics e4:43:4b:4d:ec:65 matches device eno4
2024-07-17 10:32:13.394 INFO os_net_config.objects.mapped_nics nic6 in mapping file mapped to: eno4
2024-07-17 10:32:13.394 INFO os_net_config.utils._ordered_nics Finding active nics
2024-07-17 10:32:13.394 INFO os_net_config.utils._ordered_nics enp4s0f1np1 is an active nic
2024-07-17 10:32:13.394 INFO os_net_config.utils._ordered_nics bonding_masters is not an active nic
2024-07-17 10:32:13.395 INFO os_net_config.utils._ordered_nics eno4 is an embedded active nic
2024-07-17 10:32:13.395 INFO os_net_config.utils._ordered_nics br-link2 is not an active nic
2024-07-17 10:32:13.395 INFO os_net_config.utils._ordered_nics lo is not an active nic
2024-07-17 10:32:13.395 INFO os_net_config.utils._ordered_nics eno2 is an embedded active nic
2024-07-17 10:32:13.395 INFO os_net_config.utils._ordered_nics tap27ad006e-80 is not an active nic
2024-07-17 10:32:13.395 INFO os_net_config.utils._ordered_nics vlan202 is not an active nic
2024-07-17 10:32:13.395 INFO os_net_config.utils._ordered_nics br-int is not an active nic
2024-07-17 10:32:13.396 INFO os_net_config.utils._ordered_nics ovs-netdev is not an active nic
2024-07-17 10:32:13.396 INFO os_net_config.utils._ordered_nics eno3 is an embedded active nic
2024-07-17 10:32:13.396 INFO os_net_config.utils._ordered_nics br-link1 is not an active nic
2024-07-17 10:32:13.396 INFO os_net_config.utils._ordered_nics eno1 is an embedded active nic
2024-07-17 10:32:13.397 INFO os_net_config.utils._ordered_nics bond_api is not an active nic
2024-07-17 10:32:13.397 INFO os_net_config.utils._ordered_nics enp4s0f0np0 is an active nic
2024-07-17 10:32:13.397 INFO os_net_config.utils._ordered_nics vlan203 is not an active nic
2024-07-17 10:32:13.398 INFO os_net_config.utils._ordered_nics enp4s0f0np0 is an DPDK bound nic
2024-07-17 10:32:13.399 INFO os_net_config.utils._ordered_nics enp4s0f1np1 is an DPDK bound nic
2024-07-17 10:32:13.399 INFO os_net_config.utils._ordered_nics Active nics are ['eno1', 'eno2', 'eno3', 'eno4', 'enp4s0f0np0', 'enp4s0f1np1']
2024-07-17 10:32:13.423 INFO os_net_config.impl_ifcfg.add_linux_bond adding linux bond: bond_api
2024-07-17 10:32:13.423 DEBUG os_net_config.impl_ifcfg.add_linux_bond bond data: # This file is autogenerated by os-net-config
DEVICE=bond_api
ONBOOT=yes
HOTPLUG=no
NM_CONTROLLED=no
MACADDR="e4:43:4b:4d:ec:46"
BONDING_OPTS="mode=active-backup"
BOOTPROTO=static
IPADDR=192.168 [...]

2024-07-17 13:44 UTC, karthiksundaravel approved these changes

2024-07-17 16:02 UTC, karthiksundaravel commented
recheck

2024-07-19 08:03 UTC, karthiksundaravel requested changes
Also it might be easier to get nic_mapping = json.get(‘nic_mapping’) directly

2024-07-22 09:39 UTC, abhiramnarayana commented
recheck

2024-07-22 12:06 UTC, raukadah commented
recheck ci fixed!

2024-07-23 06:23 UTC, karthiksundaravel commented
recheck

2024-07-23 06:23 UTC, karthiksundaravel approved these changes

2024-07-23 10:26 UTC, vcandapp commented
lgtm

2024-07-23 10:26 UTC, merged