Update the VF args for OvS / OvS user bridges for nmstate provider
os-net-config/os-net-config pull request #39
Opened 2024-08-01 14:34 UTC by karthiksundaravel

The default values of the VF parameters like Trust, Spoofcheck, Promisc are updated for OvS and OvS user bridges, Linux bonds. This update is not effectively applied on the nmstate provider's sriov_vf_data, leading to inconsistency between the sriov map and the VF configurations applied. Now the update of the default values are applied on sriov_vf_data.

Depends-On: https://github.com/os-net-config/os-net-config/pull/40

2024-08-01 14:55 UTC, raukadah commented
recheck

2024-08-01 14:59 UTC, raukadah commented
recheck

2024-08-02 07:07 UTC, karthiksundaravel commented
recheck

2024-08-19 12:56 UTC, vcandapp requested changes

2024-08-19 14:15 UTC, karthiksundaravel commented on os_net_config/tests/test_impl_nmstate.py
> +    def test_sriov_pf_with_custom_nicpart_ovs_user_bridge(self):
@vcandapp The testcase with custom values for sriov_vf is handled here

2024-08-19 17:47 UTC, vcandapp commented
lgtm

2024-08-19 17:47 UTC, vcandapp approved these changes

2024-08-20 18:31 UTC, merged