Allow os-net-config to run on RHEL8
os-net-config/os-net-config pull request #82
Opened 2024-09-16 18:11 UTC by karthiksundaravel

RHEL8 includes older version of libnmstate which does not include certain modules or class. This resulted in import error for the same. The import errors deny os-net-config the possibility to run with ifcfg provider.

2024-09-16 18:19 UTC, nate-johnston requested changes
I know this is DNM but I have a few improvements to suggest

2024-09-16 18:19 UTC, nate-johnston commented on os_net_config/impl_nmstate.py
> +    pass
I think there should be a log message here indicating that the libnmstate version is old and therefore the nmstate provider will not work on this version.

2024-09-16 18:19 UTC, nate-johnston commented on os_net_config/impl_nmstate.py
> +    import yaml
Can we pare down this list to the problematic set - or perhaps even just the libnmstate.schema items?  I doubt we are going to have an import issue with 're' or 'yaml'.

2024-09-17 07:47 UTC, karthiksundaravel commented
Abandoned

2024-09-17 07:47 UTC, closed without merging