WIP: Adding support for DSCP configuration
os-net-config/os-net-config pull request #9
Opened 2024-01-23 09:16 UTC by karthiksundaravel

Support dscp configuration using os-net-config templates. It uses pyroute2 modules to send/receive, encode/decode the netlink messages. The persistence of the configuration is done with dcb_config.service

2024-01-23 09:43 UTC, rjarry requested changes

2024-01-25 12:13 UTC, karthiksundaravel reviewed
Thanks Robin for the review

2024-01-25 12:13 UTC, karthiksundaravel commented on os_net_config/utils.py
> +    processutils.execute('systemctl', 'enable', 'dcb_config')
These services are expected to run during reboots, so IMHO its not necessary, isn't it ?

2024-01-25 12:13 UTC, karthiksundaravel commented on os_net_config/utils.py
> +After=NetworkManager
Agree

2024-01-25 12:13 UTC, karthiksundaravel commented on os_net_config/dcb_netlink.py
> +            )
We use only a subset of the DCB attributes. Do you think it will still be fine with upstream pyroute2 ?

2024-01-29 10:29 UTC, rjarry commented on os_net_config/utils.py
> +    processutils.execute('systemctl', 'enable', 'dcb_config')
Ok, no need.

2024-01-29 10:30 UTC, rjarry commented on os_net_config/dcb_netlink.py
> +            )
Yes, I think it should be possible. Even a partial implementation is better than nothing.

2024-01-30 08:56 UTC, rjarry requested changes
Hi @karthiksundaravel 

it looks good (just a minor nit pick about string split).

Did you consider upstreaming the changes into pyroute2?

Could you squash all commits into one and write a good commit message explaining the motivation for this patch? What is it for? Examples of use, etc.

Thanks!

2024-01-30 08:56 UTC, rjarry commented on os_net_config/utils.py
> +    'os-net-config-dcb-config.service'
Are you forced to break this line by a linter?

If not, please don't, it looks ugly :)

2024-02-22 08:54 UTC, rjarry requested changes

2024-02-22 08:54 UTC, rjarry commented on os_net_config/common.py
> +    ensure_directory_presence(filepath)
Just for reference, [`os.makedirs`](https://docs.python.org/3/library/os.html#os.makedirs) has an `exist_ok=` flag, this function is not required. You can replace it with:

```python
os.makedirs(os.path.dirname(filepath), exist_ok=True)
```

2024-02-28 06:44 UTC, vcandapp reviewed
LGTM

2024-02-28 06:46 UTC, vcandapp commented
Merging this patch for DEV_COMPLETE milestone now. Will conitue to accomodate any further review comments for this PR as follow PRs

2024-02-28 06:46 UTC, merged